# SPDX-FileCopyrightText: 2025 diffo contributors <https://github.com/diffo-dev/diffo/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule Diffo.Provider.Characteristic.Extension.Transformers.GenerateActions do
  @moduledoc """
  Synthesises default `:create` and `:update` actions on
  `BaseCharacteristic`-derived resources from the resource's declared public
  attributes.

  `:create` accepts `[:name | <public_attrs>]` with `:instance_id` and
  `:feature_id` `:uuid` arguments and corresponding `manage_relationship`
  changes. `:update` accepts `<public_attrs>` only.

  Consumers that declare their own `:create` or `:update` action take
  precedence — `add_new_action/4` will not replace an existing one.

  System attributes (`:id`, timestamps, the BaseCharacteristic `:name` slot)
  are excluded from the synthesised lists; `:name` is included on `:create`
  only.
  """
  use Spark.Dsl.Transformer

  alias Ash.Resource.Builder
  alias Spark.Dsl.Transformer

  # Attributes generated by Ash internals / BaseCharacteristic that must not
  # appear in the synthesised accept lists.
  @reserved_attrs [:id, :name, :created_at, :updated_at]

  @impl true
  def transform(dsl_state) do
    public_attrs = consumer_public_attributes(dsl_state)

    with {:ok, dsl_state} <- maybe_add_create(dsl_state, public_attrs) do
      maybe_add_update(dsl_state, public_attrs)
    end
  end

  defp consumer_public_attributes(dsl_state) do
    dsl_state
    |> Transformer.get_entities([:attributes])
    |> Enum.filter(&(Map.get(&1, :public?) && &1.name not in @reserved_attrs))
    |> Enum.map(& &1.name)
  end

  defp maybe_add_create(dsl_state, public_attrs) do
    with {:ok, instance_arg} <- Builder.build_action_argument(:instance_id, :uuid),
         {:ok, feature_arg} <- Builder.build_action_argument(:feature_id, :uuid),
         {:ok, instance_change} <-
           Builder.build_action_change(
             {Ash.Resource.Change.ManageRelationship,
              [argument: :instance_id, relationship: :instance, opts: [type: :append]]}
           ),
         {:ok, feature_change} <-
           Builder.build_action_change(
             {Ash.Resource.Change.ManageRelationship,
              [argument: :feature_id, relationship: :feature, opts: [type: :append]]}
           ) do
      Builder.add_new_action(dsl_state, :create, :create,
        accept: [:name | public_attrs],
        arguments: [instance_arg, feature_arg],
        changes: [instance_change, feature_change]
      )
    end
  end

  defp maybe_add_update(dsl_state, public_attrs) do
    Builder.add_new_action(dsl_state, :update, :update, accept: public_attrs)
  end
end
