flowchart TD
initial --> |cancel| cancelled
initial --> |feasibilityCheck| feasibilityChecked
feasibilityChecked --> |cancel| cancelled
feasibilityChecked --> |reserve| reserved
reserved --> |cancel| cancelled
reserved --> |deactivate| inactive
inactive --> |activate| active
active --> |deactivate| inactive
active --> |suspend| suspended
suspended --> |activate| active
suspended --> |terminate| terminated
terminated --> |activate| active
active --> |terminate| terminated
inactive --> |terminate| terminated
reserved --> |activate| active
feasibilityChecked --> |activate| active
initial --> |reserve| reserved
initial --> |activate| active