defmodule Diffo.Repo.Migrations.SpecificationServiceStateTransitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:specifications) do
      modify(:service_state_transitions, :binary,
        default:
          "[initial: :feasibilityChecked, initial: :reserved, initial: :inactive, initial: :active, initial: :cancelled, feasibilityChecked: :reserved, feasibilityChecked: :inactive, feasibilityChecked: :active, feasibilityChecked: :cancelled, reserved: :inactive, reserved: :active, reserved: :cancelled, inactive: :active, inactive: :terminated, active: :inactive, active: :suspended, active: :terminated, suspended: :active, suspended: :terminated]"
      )
    end
  end

  def down do
    alter table(:specifications) do
      modify(:service_state_transitions, :binary, default: nil)
    end
  end
end
