defmodule Diffo.Repo.Migrations.CharacteristicType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:characteristics) do
      modify(:relationship_id, :uuid, null: true)
      add(:type, :text, null: false)
    end

    drop_if_exists(
      unique_index(:characteristics, [:relationship_id, :name],
        name: "characteristics_unique_relationship_and_name_index"
      )
    )

    create unique_index(:characteristics, [:relationship_id, :type, :name],
             name: "characteristics_relationship_characteristic_uniqueness_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:characteristics, [:relationship_id, :type, :name],
        name: "characteristics_relationship_characteristic_uniqueness_index"
      )
    )

    create unique_index(:characteristics, [:relationship_id, :name],
             name: "characteristics_unique_relationship_and_name_index"
           )

    alter table(:characteristics) do
      remove(:type)
      modify(:relationship_id, :uuid, null: false)
    end
  end
end
