defmodule :"Elixir.Diffo.Repo.Migrations.Relationship characteristic" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:characteristics, [:relationship_id, :name],
             name: "characteristics_unique_relationship_and_name_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:characteristics, [:relationship_id, :name],
        name: "characteristics_unique_relationship_and_name_index"
      )
    )
  end
end
