defmodule Diffo.Repo.Migrations.RenameTwin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:instances), :actual_id, to: :twin_id)

    drop(constraint(:instances, "instances_actual_id_fkey"))

    alter table(:instances) do
      modify(
        :twin_id,
        references(:instances,
          column: :id,
          name: "instances_twin_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:instances, "instances_twin_id_fkey"))

    alter table(:instances) do
      modify(
        :actual_id,
        references(:instances,
          column: :id,
          name: "instances_actual_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    rename(table(:instances), :twin_id, to: :actual_id)
  end
end
