defmodule Diffo.Repo.Migrations.SpecificationServiceStateTransitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:specifications) do
      remove(:service_state_transition_map)
      add(:service_state_transitions, :binary)
    end
  end

  def down do
    alter table(:specifications) do
      remove(:service_state_transitions)
      add(:service_state_transition_map, :binary)
    end
  end
end
