defmodule Diffo.Repo.Migrations.ProcessStatuses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:process_statuses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:code, :text, null: false)
      add(:severity, :text, null: false)
      add(:message, :text, null: false)
      add(:parameterized_message, :binary)
      add(:timestamp, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "process_statuses_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    alter table(:instances) do
      remove(:process_statuses)
    end
  end

  def down do
    alter table(:instances) do
      add(:process_statuses, {:array, :map})
    end

    drop(constraint(:process_statuses, "process_statuses_instance_id_fkey"))

    drop(table(:process_statuses))
  end
end
