defmodule Diffo.Repo.Migrations.InitialInstanceResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:instances, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false, default: "service")
      add(:name, :text, null: false)
      add(:service_state, :text)
      add(:service_operating_status, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :specification_id,
        references(:specifications,
          column: :id,
          name: "instances_specification_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:instances, [:name, :specification_id],
        name: "instances_unique_name_per_specification_id_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:instances, [:name, :specification_id],
        name: "instances_unique_name_per_specification_id_index"
      )
    )

    drop(constraint(:instances, "instances_specification_id_fkey"))

    drop(table(:instances))
  end
end
