defmodule Diffo.Repo.Migrations.InstanceDatesUsec do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:instances) do
      modify(:stopped_at, :utc_datetime_usec)
      modify(:started_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:instances) do
      modify(:started_at, :utc_datetime)
      modify(:stopped_at, :utc_datetime)
    end
  end
end
