defmodule Diffo.Repo.Migrations.PlaceReferredTypeAllowNil do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:places) do
      modify(:referredType, :text, null: true)
    end
  end

  def down do
    alter table(:places) do
      modify(:referredType, :text, null: false)
    end
  end
end
