defmodule Diffo.Repo.Migrations.Entities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:entity_refs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:role, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "entity_refs_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:entity_id, :text, null: false)
    end

    create table(:entities, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
    end

    alter table(:entity_refs) do
      modify(
        :entity_id,
        references(:entities,
          column: :id,
          name: "entity_refs_entity_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create unique_index(:entity_refs, [:instance_id, :entity_id],
             name: "entity_refs_instance_entity_uniqueness_index"
           )

    alter table(:entities) do
      add(:href, :text)
      add(:name, :text)
      add(:type, :text, null: false, default: "EntityRef")
      add(:referredType, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:entities) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:referredType)
      remove(:type)
      remove(:name)
      remove(:href)
    end

    drop_if_exists(
      unique_index(:entity_refs, [:instance_id, :entity_id],
        name: "entity_refs_instance_entity_uniqueness_index"
      )
    )

    drop(constraint(:entity_refs, "entity_refs_entity_id_fkey"))

    alter table(:entity_refs) do
      modify(:entity_id, :text)
    end

    drop(table(:entities))

    drop(constraint(:entity_refs, "entity_refs_instance_id_fkey"))

    drop(table(:entity_refs))
  end
end
