defmodule Diffo.Repo.Migrations.InstanceDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:instances) do
      add(:started_at, :utc_datetime)
      add(:stopped_at, :utc_datetime)
    end
  end

  def down do
    alter table(:instances) do
      remove(:stopped_at)
      remove(:started_at)
    end
  end
end
