defmodule Diffo.Repo.Migrations.SpecificationStrategy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:specifications) do
      add(:strategy, :map)
    end

    alter table(:instances) do
      modify(:service_operating_status, :text, default: "unknown")
      modify(:service_state, :text, default: "initial")
    end
  end

  def down do
    alter table(:instances) do
      modify(:service_state, :text, default: nil)
      modify(:service_operating_status, :text, default: nil)
    end

    alter table(:specifications) do
      remove(:strategy)
    end
  end
end
