defmodule Diffo.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:specifications) do
      add(:which, :text, null: false, default: "actual")
    end

    drop_if_exists(
      unique_index(:specifications, [:name, :major_version],
        name: "specifications_unique_major_version_per_name_index"
      )
    )

    create unique_index(:specifications, [:name, :major_version, :which],
             name: "specifications_unique_major_version_per_name_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:specifications, [:name, :major_version, :which],
        name: "specifications_unique_major_version_per_name_index"
      )
    )

    create unique_index(:specifications, [:name, :major_version],
             name: "specifications_unique_major_version_per_name_index"
           )

    alter table(:specifications) do
      remove(:which)
    end
  end
end
