defmodule :"Elixir.Diffo.Repo.Migrations.Expected specification" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:specifications) do
      add(:expected_id, :binary)
      add(:expected_name, :binary)
      add(:expected_version, :binary)
    end
  end

  def down do
    alter table(:specifications) do
      remove(:expected_version)
      remove(:expected_name)
      remove(:expected_id)
    end
  end
end
