defmodule Diffo.Repo.Migrations.InstanceTypeCalculated do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:instances) do
      remove(:type)
    end
  end

  def down do
    alter table(:instances) do
      add(:type, :text, null: false, default: "service")
    end
  end
end
