defmodule Diffo.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:specifications, primary_key: false) do
      add(:type, :text, null: false, default: "serviceSpecification")
      add(:name, :text, null: false)
      add(:major_version, :bigint, null: false, default: 1)

      add(:id, :uuid,
        null: false,
        default: "fe624d58-f1e0-4bce-864c-14a176fbae94",
        primary_key: true
      )

      add(:description, :text)
      add(:version, :text)
      add(:href, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:specifications))
  end
end
