defmodule Diffo.Repo.Migrations.UpdateIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:specifications, [:name, :type],
        name: "specifications_unique_type_per_name_index"
      )
    )
  end

  def down do
    create(
      unique_index(:specifications, [:name, :type],
        name: "specifications_unique_type_per_name_index"
      )
    )
  end
end
