defmodule Diffo.Repo.Migrations.RelationshipRefactorOneWay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:relationships) do
      remove(:reverse_type)
    end
  end

  def down do
    alter table(:relationships) do
      add(:reverse_type, :text)
    end
  end
end
