defmodule Diffo.Repo.Migrations.InstanceCharacteristic do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:characteristics) do
      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "characteristics_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:characteristics, [:instance_id, :name],
             name: "characteristics_instance_characteristic_uniqueness_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:characteristics, [:instance_id, :name],
        name: "characteristics_instance_characteristic_uniqueness_index"
      )
    )

    drop(constraint(:characteristics, "characteristics_instance_id_fkey"))

    alter table(:characteristics) do
      remove(:instance_id)
    end
  end
end
