defmodule Diffo.Repo.Migrations.InitialPlaceAndPlaceRef do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:places, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:href, :text)
      add(:name, :text)
      add(:type, :text, null: false, default: "PlaceRef")
      add(:referredType, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:place_refs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:role, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "place_refs_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :place_id,
        references(:places,
          column: :id,
          name: "place_refs_place_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:place_refs, [:instance_id, :place_id],
             name: "place_refs_instance_place_uniqueness_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:place_refs, [:instance_id, :place_id],
        name: "place_refs_instance_place_uniqueness_index"
      )
    )

    drop(constraint(:place_refs, "place_refs_instance_id_fkey"))

    drop(constraint(:place_refs, "place_refs_place_id_fkey"))

    drop(table(:place_refs))

    drop(table(:places))
  end
end
