defmodule Diffo.Repo.Migrations.Features do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:features, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:isEnabled, :boolean, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "features_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:features, [:instance_id, :name],
             name: "features_instance_feature_uniqueness_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:features, [:instance_id, :name],
        name: "features_instance_feature_uniqueness_index"
      )
    )

    drop(constraint(:features, "features_instance_id_fkey"))

    drop(table(:features))
  end
end
