defmodule Diffo.Repo.Migrations.Notes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:process_statuses) do
      remove(:updated_at)
      remove(:inserted_at)
    end

    create table(:notes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:text, :text, null: false)
      add(:note_id, :text)
      add(:timestamp, :utc_datetime_usec, null: false)

      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "notes_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :author_id,
        references(:parties,
          column: :id,
          name: "notes_author_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create unique_index(:notes, [:instance_id, :note_id],
             name: "notes_instance_note_id_uniqueness_index"
           )

    create unique_index(:notes, [:instance_id, :text],
             name: "notes_instance_text_uniqueness_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:notes, [:instance_id, :text], name: "notes_instance_text_uniqueness_index")
    )

    drop_if_exists(
      unique_index(:notes, [:instance_id, :note_id],
        name: "notes_instance_note_id_uniqueness_index"
      )
    )

    drop(constraint(:notes, "notes_instance_id_fkey"))

    drop(constraint(:notes, "notes_author_id_fkey"))

    drop(table(:notes))

    alter table(:process_statuses) do
      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end
end
