defmodule Diffo.Repo.Migrations.InstanceKeyRefactor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:specifications) do
      modify(:id, :uuid, default: nil)
    end

    alter table(:instances) do
      modify(:id, :uuid, default: nil)
    end
  end

  def down do
    alter table(:instances) do
      modify(:id, :uuid, default: fragment("gen_random_uuid()"))
    end

    alter table(:specifications) do
      modify(:id, :uuid, default: fragment("gen_random_uuid()"))
    end
  end
end
