defmodule Diffo.Repo.Migrations.ExternalIdentifier do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:externalIdentifiers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)
      add(:external_id, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :instance_id,
        references(:instances,
          column: :id,
          name: "externalIdentifiers_instance_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :owner_id,
        references(:parties,
          column: :id,
          name: "externalIdentifiers_owner_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create unique_index(:externalIdentifiers, [:instance_id, :type],
             name: "externalIdentifiers_instance_type_uniqueness_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:externalIdentifiers, [:instance_id, :type],
        name: "externalIdentifiers_instance_type_uniqueness_index"
      )
    )

    drop(constraint(:externalIdentifiers, "externalIdentifiers_instance_id_fkey"))

    drop(constraint(:externalIdentifiers, "externalIdentifiers_owner_id_fkey"))

    drop(table(:externalIdentifiers))
  end
end
