defmodule Diffo.Provider.CharacteristicRef do
  @moduledoc """
  Diffo - TMF Service and Resource Management with a difference

  CharacteristicRef - Ash Resource joining Instance to Characteristic
  """
  use Ash.Resource,
    otp_app: :diffo,
    domain: Diffo.Provider,
    data_layer: AshNeo4j.DataLayer,
    extensions: [AshOutstanding.Resource, AshJason.Resource]

  resource do
    description "An Ash Resource for a TMF Characteristic Reference"
    plural_name :characteristicRefs
  end

  neo4j do
    relate [
      {:instance, :RELATES, :incoming, :Instance},
      {:characteristic, :RELATES, :outgoing, :Characteristic}
    ]
  end

  jason do
    pick [:characteristic]
  end

  outstanding do
    expect [:characteristic_id, :name, :role, :referredType, :type]
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      description "creates a characteristic ref, relating an instance and a characteristic"
      accept [:role]

      argument :instance_id, :uuid
      argument :characteristic_id, :string

      change manage_relationship(:instance_id, :instance, type: :append_and_remove)
      change manage_relationship(:characteristic_id, :characteristic, type: :append_and_remove)
    end

    read :list do
      description "lists all characteristic refs"
    end

    read :list_characteristic_refs_by_instance_id do
      description "lists characteristic refs by instance id"
      argument :instance_id, :uuid
      filter expr(instance_id == ^arg(:instance_id))
    end

    read :list_characteristic_refs_by_characteristic_id do
      description "lists characteristic refs by characteristic id"
      argument :characteristic_id, :string
      filter expr(characteristic_id == ^arg(:characteristic_id))
    end

    read :find_by_characteristic_id do
      description "finds characteristic refs by characteristic id"
      get? false

      argument :query, :ci_string do
        description "Return only characteristic refs with characteristic_ids including the given value."
      end

      filter expr(contains(characteristic_id, ^arg(:query)))
    end

    update :update do
      description "updates the characteristic ref role"
      accept [:role]
    end
  end

  attributes do
    uuid_primary_key :id do
      description "a uuid4, unique to this characteristic ref, generated by default"
      public? false
    end

    attribute :role, :atom do
      description "the role of the characteristic to the instance"
      allow_nil? true
      public? true
      default :uses
    end

    create_timestamp :inserted_at

    update_timestamp :updated_at
  end

  relationships do
    belongs_to :instance, Diffo.Provider.Instance do
      description "the instance which relates to a characteristic via this characteristic ref"
      allow_nil? false
      public? true
    end

    belongs_to :characteristic, Diffo.Provider.Characteristic do
      description "the characteristic which is related from an instance via this characteristic ref"
      allow_nil? false
      public? true
    end
  end

  identities do
    identity :instance_characteristic_uniqueness, [:instance_id, :characteristic_id] do
      message "another characteristic ref exists"
    end
  end

  preparations do
    prepare build(
              load: [:characteristic],
              sort: [role: :asc, inserted_at: :desc]
            )
  end

  @doc """
  Compares two characteristic ref, by ascending characteristic_id
  ## Examples
    iex> Diffo.Provider.CharacteristicRef.compare(%{characteristic_id: "a"}, %{characteristic_id: "a"})
    :eq
    iex> Diffo.Provider.CharacteristicRef.compare(%{characteristic_id: "b"}, %{characteristic_id: "a"})
    :gt
    iex> Diffo.Provider.CharacteristicRef.compare(%{characteristic_id: "a"}, %{characteristic_id: "b"})
    :lt

  """
  def compare(%{characteristic_id: characteristic_id0}, %{characteristic_id: characteristic_id1}),
    do: Diffo.Util.compare(characteristic_id0, characteristic_id1)
end
