# SPDX-FileCopyrightText: 2025 diffo contributors <https://github.com/diffo-dev/diffo/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule Diffo.Provider.Event do
  @moduledoc """
  Diffo - TMF Service and Reource Management with a difference

  Event - Ash Resource for a TMF Event
  """
  use Ash.Resource,
    otp_app: :diffo,
    domain: Diffo.Provider,
    data_layer: AshNeo4j.DataLayer,
    extensions: [AshOutstanding.Resource, AshJason.Resource]

  alias Diffo.Util, as: Util

  resource do
    description "An Ash Resource for a TMF Entity Reference"
    plural_name :events
  end

  code_interface do
    define :create
    define :destroy
  end

  neo4j do
    relate [
      {:instance, :FIRED, :incoming, :Instance}
      # {:earlier_event, :AFTER, :outgoing, :Event}
    ]
  end

  jason do
    pick [:id, :created_at, :type, :instance]
    rename id: :eventId, created_at: :eventTime, type: :eventType

    customize fn result, record ->
      result
      |> __MODULE__.time(record)
      |> Util.rename(:instance, record.instance_type)
      |> Util.nest_as_map([record.instance_type], :event)
    end

    order [:eventId, :eventTime, :eventType, :event]
  end

  outstanding do
    expect [:type, :created_at, :instance_id, :instance]
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      description "creates an event, fired by an instance"
      accept [:type]
      argument :instance_id, :uuid
      # argument :earlier_event_id, :uuid

      change manage_relationship(:instance_id, :instance, type: :append_and_remove)
      # change manage_relationship(:earlier_event_id, :earlier_event, type: :append_and_remove)
      change load [:instance_type, :instance]
    end

    read :list do
      description "lists all events"
    end

    read :list_events_by_instance_id do
      description "lists events by instance id"
      argument :instance_id, :uuid
      filter expr(instance_id == ^arg(:instance_id))
    end
  end

  attributes do
    uuid_primary_key :id do
      description "a uuid4, unique to this entity ref, generated by default"
      public? false
    end

    attribute :type, :atom do
      description "the type of the event"
      allow_nil? false
      public? true

      constraints one_of: [
                    :serviceCreateEvent,
                    :serviceStateChangeEvent,
                    :serviceAttributeValueChangeEvent,
                    :serviceDeleteEvent,
                    :resourceCreateEvent,
                    :resourceStateChangeEvent,
                    :resourceAttributeValueChangeEvent,
                    :resourceDeleteEvent
                  ]
    end

    create_timestamp :created_at

    update_timestamp :updated_at
  end

  relationships do
    belongs_to :instance, Diffo.Provider.Instance do
      description "the instance which fired the event"
      allow_nil? false
      public? true
    end

    # has_one :earlier_event, Diffo.Provider.Event do
    #  description "the earlier event, if any"
    #  allow_nil? true
    #  public? true
    # end
  end

  calculations do
    calculate :instance_type,
              :atom,
              expr(instance.type) do
      description "the type of the instance which fired the event"
    end
  end

  preparations do
    prepare build(load: [:instance_type, :instance], sort: [created_at: :desc])
  end

  @spec time([tuple()], any()) :: [tuple()]
  @doc """
  Assists in encoding event time
  """
  def time(result, record) do
    result
    |> Diffo.Util.set(
      :eventTime,
      Diffo.Util.to_iso8601(record.created_at)
    )
  end

  @doc """
  Compares two event, by id
  ## Examples
    iex> Diffo.Provider.Event.compare(%{id: "a"}, %{id: "a"})
    :eq
    iex> Diffo.Provider.Event.compare(%{id: "b"}, %{id: "a"})
    :gt
    iex> Diffo.Provider.Event.compare(%{id: "a"}, %{id: "b"})
    :lt

  """
  def compare(%{id: id0}, %{id: id1}),
    do: Diffo.Util.compare(id0, id1)
end
