# SPDX-FileCopyrightText: 2025 diffo contributors <https://github.com/diffo-dev/diffo/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule Diffo.Provider.Event do
  @moduledoc """
  Ash Resource for a TMF Event
  """
  use Ash.Resource,
    otp_app: :diffo,
    domain: Diffo.Provider,
    data_layer: AshNeo4j.DataLayer,
    extensions: [AshOutstanding.Resource, AshJason.Resource]

  alias Diffo.Util, as: Util

  resource do
    description "An Ash Resource for a TMF Entity Reference"
    plural_name :events
  end

  code_interface do
    define :create
    define :destroy
  end

  neo4j do
    relate [
      {:instance, :FIRED, :incoming, :Instance},
      {:later, :AFTER, :incoming, :Event},
      {:earlier, :AFTER, :outgoing, :Event}
    ]
  end

  jason do
    rename id: :eventId, created_at: :eventTime, type: :eventType

    customize fn result, record ->
      result
      |> __MODULE__.time(record)
      |> Util.fragment(:firing_snapshot)
      |> Util.rename(:firing_snapshot, record.firing_type)
      |> Util.nest_as_map([record.firing_type], :event)
    end

    order [:eventId, :eventTime, :eventType, :event]
  end

  outstanding do
    expect [:type, :created_at, :instance_id, :firing_type, :firing_snapshot]
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      description "creates an event, fired by an instance, optionally related to earlier event"
      primary? true
      accept [:type, :firing_type, :firing_snapshot]
      argument :instance_id, :uuid
      argument :earlier_id, :uuid

      change manage_relationship(:instance_id, :instance, type: :append)
      change manage_relationship(:earlier_id, :earlier, type: :append_and_remove)
    end

    read :list do
      description "lists all events"
    end

    read :list_events_by_instance_id do
      description "lists events by instance id"
      argument :instance_id, :uuid
      filter expr(instance_id == ^arg(:instance_id))
    end
  end

  attributes do
    uuid_primary_key :id do
      description "a uuid4, unique to this event, generated by default"
      public? true
    end

    attribute :instance_id, :uuid do
      description "the id of the instance that fired the event"
      allow_nil? true
      public? true
    end

    attribute :firing_type, :atom do
      description "the type of resource that fired the event"
      allow_nil? true
      public? true
    end

    attribute :firing_snapshot, :string do
      description "the json serialisation of the resource which fired the event"
      allow_nil? true
      public? true
    end

    attribute :type, :atom do
      description "the type of the event"
      allow_nil? false
      public? true

      constraints one_of: [
                    :serviceCreateEvent,
                    :serviceStateChangeEvent,
                    :serviceAttributeValueChangeEvent,
                    :serviceDeleteEvent,
                    :resourceCreateEvent,
                    :resourceStateChangeEvent,
                    :resourceAttributeValueChangeEvent,
                    :resourceDeleteEvent
                  ]
    end

    create_timestamp :created_at

    update_timestamp :updated_at
  end

  relationships do
    belongs_to :instance, Diffo.Provider.Instance,
      allow_nil?: true,
      public?: true,
      source_attribute: :instance_id

    belongs_to :later, Diffo.Provider.Event,
      allow_nil?: true,
      public?: true,
      source_attribute: :later_id

    belongs_to :earlier, Diffo.Provider.Event,
      allow_nil?: true,
      public?: true,
      source_attribute: :earlier_id
  end

  preparations do
    prepare build(sort: [created_at: :desc])
  end

  @spec time([tuple()], any()) :: [tuple()]
  @doc """
  Assists in encoding event time
  """
  def time(result, record) do
    result
    |> Diffo.Util.set(
      :eventTime,
      Diffo.Util.to_iso8601(record.created_at)
    )
  end
end
