# SPDX-FileCopyrightText: 2025 diffo contributors <https://github.com/diffo-dev/diffo/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule Diffo.Provider.PlaceRef do
  @moduledoc """
  Diffo - TMF Service and Resource Management with a difference

  PlaceRef - Ash Resource for a TMF Place Reference
  """
  use Ash.Resource,
    otp_app: :diffo,
    domain: Diffo.Provider,
    data_layer: AshNeo4j.DataLayer,
    extensions: [AshOutstanding.Resource, AshJason.Resource]

  resource do
    description "An Ash Resource for a TMF Place Reference"
    plural_name :placeRefs
  end

  neo4j do
    relate [
      {:instance, :RELATES, :incoming, :Instance},
      {:party, :RELATES, :incoming, :Party},
      {:source_place, :RELATES, :incoming, :Place},
      {:place, :RELATES, :outgoing, :Place}
    ]
  end

  jason do
    pick [:role, :place]

    customize fn result, _record ->
      result
      |> Diffo.Util.extract_suppress(:place, :id, :id)
      |> Diffo.Util.extract_suppress(:place, :href, :href)
      |> Diffo.Util.extract_suppress(:place, :name, :name)
      |> Diffo.Util.extract_suppress(:place, :referredType, "@referredType")
      |> Diffo.Util.extract_suppress(:place, :type, "@type")
      |> Diffo.Util.remove(:place)
    end

    order [:id, :href, :name, :role, "@referredType", "@type"]
  end

  outstanding do
    expect [:role, :place]
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      description "creates a place ref, relating an instance, party or source place to a place"
      accept [:role]
      argument :instance_id, :uuid
      argument :party_id, :string
      argument :source_place_id, :string
      argument :place_id, :string

      change manage_relationship(:instance_id, :instance, type: :append_and_remove)
      change manage_relationship(:party_id, :party, type: :append_and_remove)
      change manage_relationship(:source_place_id, :source_place, type: :append_and_remove)
      change manage_relationship(:place_id, :place, type: :append_and_remove)
    end

    read :list do
      description "lists all place refs"
    end

    read :list_place_refs_by_instance_id do
      description "lists place refs by instance id"
      argument :instance_id, :uuid
      filter expr(instance_id == ^arg(:instance_id))
    end

    read :list_place_refs_by_party_id do
      description "lists place refs by party id"
      argument :party_id, :string
      filter expr(party_id == ^arg(:party_id))
    end

    read :list_place_refs_by_source_place_id do
      description "lists place refs by source_place id"
      argument :source_place_id, :string
      filter expr(source_place_id == ^arg(:source_place_id))
    end

    read :list_place_refs_by_place_id do
      description "lists place refs by place id"
      argument :place_id, :string
      filter expr(place_id == ^arg(:place_id))
    end

    update :update do
      description "updates the place ref role"
      accept [:role]
    end
  end

  attributes do
    uuid_primary_key :id do
      description "a uuid4, unique to this place ref, generated by default"
      public? false
    end

    attribute :role, :atom do
      description "the role of the place to the instance, party or source place"
      allow_nil? true
      public? true
    end

    create_timestamp :created_at

    update_timestamp :updated_at
  end

  relationships do
    belongs_to :instance, Diffo.Provider.Instance do
      description "the instance which relates to a place via this place ref"
      allow_nil? true
      public? true
    end

    belongs_to :party, Diffo.Provider.Party do
      description "the party which relates to a place via this place ref"
      attribute_type :string
      allow_nil? true
      public? true
    end

    belongs_to :source_place, Diffo.Provider.Place do
      description "the source place which relates to a place via this place ref"
      attribute_type :string
      allow_nil? true
      public? true
    end

    belongs_to :place, Diffo.Provider.Place do
      description "the place which is related from an instance via this place ref"
      attribute_type :string
      allow_nil? false
      public? true
    end
  end

  identities do
    identity :instance_place_uniqueness, [:instance_id, :place_id] do
      message "another place ref exists relating the same instance and place"
    end

    identity :party_place_uniqueness, [:party_id, :place_id] do
      message "another place ref exists"
    end

    identity :source_place_place_uniqueness, [:source_place_id, :place_id] do
      message "another place ref exists"
    end
  end

  validations do
    validate present([:instance_id, :party_id, :source_place_id], exactly: 1) do
      message "a place ref can relate either an instance, party or source place"
    end
  end

  preparations do
    prepare build(
              load: [:place],
              sort: [role: :asc, created_at: :desc]
            )
  end

  @doc """
  Compares two place ref, by ascending place_id
  ## Examples
    iex> Diffo.Provider.PlaceRef.compare(%{place_id: "a"}, %{place_id: "a"})
    :eq
    iex> Diffo.Provider.PlaceRef.compare(%{place_id: "b"}, %{place_id: "a"})
    :gt
    iex> Diffo.Provider.PlaceRef.compare(%{place_id: "a"}, %{place_id: "b"})
    :lt

  """
  def compare(%{place_id: place_id0}, %{place_id: place_id1}),
    do: Diffo.Util.compare(place_id0, place_id1)
end
